### ISSUE TITLE
Nivel 2 | Uso de teclas para navegar por la BIOS 

### ISSUE THREAD

**Issue by diegxherrera** [diegxherrera/Escapeuropa#7]
Utilización de las **teclas** para dar un mayor realismo a la BIOS, desactivación del cursor para esta parte del Nivel 2.
![Screen Shot 2022-02-03 at 12 30 03 AM](https://user-images.githubusercontent.com/78816554/152255149-0c4932bb-aaed-4fac-82b0-58198cccc990.png)

**Comment by Letder40** [comment]
Ha día de hoy sigo sin ver cómo implementarlo. 
En estudio

**Comment by nicogarcia0** [comment]
Lo he estado haciendo yo, lo tengo casi listo ya he subido lo que llevo, falta solo que se pueda controlar el menu de hardrive del apartado boot que lo estoy haciendo
